AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dakobed Rest API Service
Parameters:
  BucketName:
    Type: String
    Default: dakobed-sqs-transform-bucket
Resources:
  UploadApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UploadApi
      StageName: Prod
      DefinitionUri: s3://dakobed-serverless-apis/6e336f40ded4903c0f8b38ff2b2739df
  PresignedPostUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      FunctionName: PresignedPostUploadFunction
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: BucketName
      - AWSLambdaBasicExecutionRole
      - DynamoDBCrudPolicy:
          TableName: UserUploads
      CodeUri: s3://dakobed-serverless-apis/9b2b070225c12959fc392cf1bf221ed0
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          UploadBucket:
            Ref: BucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: UploadApi
            Path: /signedURL
            Method: POST
  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - UploadApi
    - PresignedPostUploadFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PresignedPostUploadFunction
      Principal: apigateway.amazonaws.com
  S3UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - '*'
          AllowedMethods:
          - GET
          - PUT
          - HEAD
          - POST
          AllowedOrigins:
          - '*'
  ProcessUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      FunctionName: ProcessUploadFunction
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: BucketName
      - AWSLambdaBasicExecutionRole
      - DynamoDBCrudPolicy:
          TableName: UserUploads
      CodeUri: s3://dakobed-serverless-apis/25595c94dd227b9b17a7867807cfc983
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          UploadBucket:
            Ref: BucketName
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: UploadApi
            Path: /upload
            Method: put
  ProcessFunctionLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - UploadApi
    - ProcessUploadFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ProcessUploadFunction
      Principal: apigateway.amazonaws.com
Outputs:
  UploadApi:
    Description: API Gateway endpoint URL for Prod stage upload API
    Value:
      Fn::Sub: https://${UploadApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - UploadApi
  S3UploadBucket:
    Description: API Gateway endpoint URL for Prod stage upload API
    Value:
      Ref: BucketName
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - S3UploadBucket
  UploadBucketARN:
    Description: API Gateway endpoint URL for Prod stage upload API
    Value:
      Fn::GetAtt:
      - S3UploadBucket
      - Arn
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - upload-bucket-arn
